### PR TITLE
Fix Ancient Greek transcription errors

### PR DESCRIPTION
**Pull request by johnfactotum**
The change was made with the following Node.js script. It does the following:

- Normalize the text to NFKD. This fixes the `ϕ` vs `φ` problem. But it has the side effect of turning `…` into `...` which needs to be reversed later.
- Fix common errors such as `w > ω`, `a > α`, etc.
- Normalize again to NFC.

It's not perfect, but it should fix most of the issues mentioned in #3.

```js
#!/usr/bin/env node
const path = require('path')
const fs = require('fs')
const { JSDOM } = require('jsdom')

const dir = './plato_dialogues_benjamin-jowett'
const textPath = path.join(dir, 'src/epub/text')

const table = [
    ['\u0302', '\u0342'], // circumflex -> perispomeni
    ['\u0323', '\u0345'], // dot below -> ypogegrammeni
    ['a', 'α'],
    ['i', 'ι'],
    ['ɩ', 'ι'], // Latin iota -> Greek iota
    ['o', 'ο'], // Latin o -> Greek omicron
    ['w', 'ω'],
    [/ν(?=\p{Mn})/gu, 'υ'],
]

const dom = new JSDOM()
const { DOMParser } = dom.window
const parser = new DOMParser()

for (const name of fs.readdirSync(textPath)) {
    const file = path.join(textPath, name)
    let text = fs.readFileSync(file, 'utf8')

    const doc = parser.parseFromString(text, 'application/xhtml+xml')
    const grc = doc.querySelectorAll('[xml\\:lang="grc"]')
    if (!grc.length) continue

    for (const el of grc) {
        const iter = doc.createNodeIterator(el, 4)
        for (let node = iter.nextNode(); node; node = iter.nextNode()) {
            const source = node.nodeValue
            let str = source.normalize('NFKD')
            for (const [a, b] of table) str = str.replaceAll(a, b)
            const result = str.normalize('NFC').replaceAll('...', '…')
            if (!text.includes(source))
                throw new Error('failed to replace string: ' + source)
            text = text.replace(source, result)
        }
    }
    fs.writeFileSync(file, text)
}
```

### CODE REVIEW

**Comment by acabal** [comment]
Great John thanks, this looks really good!

I wonder if you could turn this into a Python function? I glanced over a few of the changes and they look pretty accurate. If we could get this as a Python function, we could add a check to `se lint` where all Greek text is run through the function and if it doesn't match the expected value, the producer is alerted to review the transcription.

Using our SE XML helper classes, some pseudocode might look something like this:

````python
def is_greek_correct(dom):
    # `dom` is an se.EasyXmlTree, already prepared for use in the body of se.SeEpub.lint()
    # `nodes` is a list of se.EasyXmlElement
    nodes = dom.xpath("//*[@xml:lang='grc']")
    for node in nodes:
        node_contents = node.inner_text()
        # `node_contents` is a string containing the inner text of the node without any markup
        # Now process `node_contents` into `expected_contents`
        expected_contents = ...
        if node_contents != expected_contents:
             print(f"Greek transcription needs to be reviewed: {node_contents}, but expected {expected_contents}")
````

If you can put together a self contained function like that, then I can inline it into our lint tool. Or, you could even do a complete PR if you're feeling adventurous. `se_epub_lint.py` is quite large, but it's mostly just repeating a few basic patterns, so it's not as complex as it might first appear.

**Comment by acabal** [comment]
I also wonder about non-Ancient Greek transcriptions. I know the diacritic system is different but would this process help in finding errors in modern Greek, i.e. `xml:lang="el"`?

**Comment by acabal** [comment]
By the way, since normalizing the text fixes theta, does it also fix kappa like in Moby Dick?

**Comment by johnfactotum** [comment]
> I also wonder about non-Ancient Greek transcriptions.

At first I thought one could improve the existing Latin script check (`[a-zA-Z]`) by using `\p{Script=Latin}` instead. And more specifically one could also use `[^\p{Script=Greek}]` to check non-Greek characters. In JavaScript,
```js
"τŵν".match(/\p{Script=Latin}/u)
// ["ŵ"]

"νν̂ν".match(/[^\p{Script=Greek}]/u)
// ["̂"]
```

But apparently this doesn't work with the `regex` module in Python for some reason.
```python
regex.match(r'\p{Script=Latin}', 'τŵν')
# None

regex.match(r'[^\p{Script=Greek}]', 'νν̂ν')
# None
```

But if one could get `regex` to support this (or else manually build a regex containing the range of characters for the scripts, using the Unicode Character Database), this should work for linting.

> By the way, since normalizing the text fixes theta, does it also fix kappa like in Moby Dick?

Yes. And in general, I think running a normalization step with compatibility equivalence (i.e. NFKC or NFKD) for the whole text would be a good idea. Although it's quite heavy handed, I would expect it to output better results than if you don't normalize or normalize only using canonical equivalence (i.e. NFC or NFD).

There might be some cases where you don't want to normalize things this way. For example, if the kappa is used in a mathematical expression in a Latin script context, then it's not wrong to use the kappa *symbol*. But it's not wrong to use the kappa *letter*, either. In fact, it might be preferred.

Semantic differences for compatibility equivalent characters are, I believe, mostly only typographical. If you can render the text with the appropriate HTML markup and CSS styles, you will probably want to use the compatibility equivalent form in most cases. Even for something like the ellipsis, or the different kinds of dash or space, for example, they are mostly used for typographical reasons only, so even these could (at least in theory) be normalized using compatibility equivalence, and the rendering differences can be achieved with CSS.

**Comment by acabal** [comment]
Not sure about normalizing each ebook as a matter of course. Probably 80% of books are pure English so it wouldn't make much difference except for some very old PG transcriptions that might use letter + combining mark instead of the single character variant of a glyph like `é`. I feel like this is something I must have addressed in the tools in the past, though I can't remember right now, so maybe I didn't. And it might introduce other problems like `...` which happened here, and other subtle problems that would be difficult to see in a text editor.

If you want to, you can explore the pros/cons of normalization by testing on our corpus first to see how it might go, and if it would even be helpful at all. If it does seem to help then we can certainly add tooling for that.

Any interest in putting this Greek work into Python? I'd love to have this check in lint, but I'm too busy right now. If you don't have time either, then we'll shelve it for now and add it to a long list of to-dos for someone to pick up later.

**Comment by johnfactotum** [comment]
Like this?

```py
import regex
import unicodedata

def is_greek_correct(dom):
    table = [
        ('\u0302', '\u0342'), # circumflex -> perispomeni
        ('\u0323', '\u0345'), # dot below -> ypogegrammeni
        ('a', 'α'),
        ('i', 'ι'),
        ('ɩ', 'ι'), # Latin iota -> Greek iota
        ('o', 'ο'), # Latin o -> Greek omicron
        ('w', 'ω'),
        (r'ν(?=\p{Mn})', 'υ'),
    ]
    nodes = dom.xpath("//*[@xml:lang='grc']")
    for node in nodes:
        node_contents = unicodedata.normalize('NFKC', node.inner_text())
        expected_contents = node_contents
        for a, b in table: expected_contents = regex.sub(a, b, expected_contents)
        expected_contents = unicodedata.normalize('NFC', expected_contents)
        if node_contents != expected_contents:
             print(f"Greek transcription needs to be reviewed: {node_contents}, but expected {expected_contents}")
```

**Comment by acabal** [comment]
Great! One issue that has come up is that NFKC normalization changes `U+1FBF GREEK PSILI` to `U+0313 COMBINING COMMA ABOVE`, for example:

`καθ᾿` -> `καθ ̓`

This doesn't seem right to me. Is replacing a Greek psili with a generic combining comma really what we want here?

**Comment by johnfactotum** [comment]
Both are wrong, I think. It should be an apostrophe, indicating an elided vowel. See https://en.wiktionary.org/wiki/%CE%BA%CE%B1%CE%B8%27. I guess one could fix this by making sure that all diacritics follow either vowels or other diacritics.

**Comment by johnfactotum** [comment]
But note that the combining comma is indeed the correct character in general. Quote from the Unicode Standard:

> Because the characters in the Combining Diacritical Marks block are encoded by shape, not by meaning, they are appropriate for use in Greek where applicable.

Unlike the perispomeni, there's no combining psili. So for example, `ἀ` (U+1F00) is *canonically* equivalent to `ἀ` (U+03B1 and U+0313). The perispomeni is encoded separately because its shape can either a tilde or an inverted breve.

The non-combining psili U+1FBF is not really appropriate for ordinary Greek text. From the Unicode Standard:

> Sixteen additional spacing diacritical marks are provided in this character block for use in the representation of polytonic Greek texts. Each has an alternative representation for use with systems that support nonspacing marks. [...] The spacing forms are meant for keyboards and pedagogical use and are not to be used in the representation of titlecase words.

**Comment by acabal** [comment]
This is quite the rabbit hole and much more complex than expected!

I'm reading the [Unicode Greek FAQ](https://www.unicode.org/faq/greek.html) which points to [this page](http://www.opoudjis.net/unicode/unicode.html) as a end-of-the-line resource for Greek Unicode.

[Here](http://www.opoudjis.net/unicode/punctuation.html#singlequotes) he suggests that rsquo should not be used: 

> In fact, as the Unicode Standard [notes](http://www.unicode.org/versions/Unicode4.0.0/ch07.pdf) (§7.2), single quotation marks are best avoided with polytonic Greek in general; the risk of confusion with apostrophes and breathings is just too great—not to mention the jarring effect of a single quote in front of a titlecase rough breathing

The table in the Unicode standard which you linked to does indeed say that `U+1FBF GREEK PSILI` decomposes to `U+0020 SPACE U+0313 COMBINING COMMA ABOVE` so I'm at least satisfied that the normalization in your script was correct in that case.

Based on the above quote I'm not entirely convinced rsquo is actually the right choice - that is, unless the psili in my specific example was not intended to be a psili at all, but rather was a mistranscription of some other symbol to begin with.

The other question the normalization brings up, is why does the normalization add a space before `U+0303`? That clearly looks wrong especially when, as you note, there exist characters like `ἀ` in which the psili is plainly combined with the letter.

Are you fluent in Greek? I feel like much of my struggle in understanding the complexities of Greek Unicode is that I don't speak a word of it!

**Comment by johnfactotum** [comment]
> that is, unless the psili in my specific example was not intended to be a psili at all

It's not the psili, per se. It's an apostrophe that indicates that the vowel is elided. The advice that single quotes should not be be used means that, for *quotations*, you should use double quotes or french quotes instead, as single quotes would be confused with the breathing marks or apostrophe. But the question here is: which character should you use for the *apostrophe*? Logically, the usual apostrophe punctuation mark, U+2019, should be used. But some people use the psili for typographical reasons even though it's semantically incorrect. See https://www.opoudjis.net/unicode/gkdiacritics.html#apostrophe.

> Are you fluent in Greek?

I'm not. I did take two semesters of Ancient Greek a long time ago. So I have only a very basic understanding of the language.

**Comment by johnfactotum** [comment]
> The other question the normalization brings up, is why does the normalization add a space before `U+0303`? That clearly looks wrong especially when, as you note, there exist characters like `ἀ` in which the psili is plainly combined with the letter.

U+1FBF Greek Psili is a spacing, non-combining character. These characters in the Greek Extended block are equivalent to a space plus the non-spacing, combining form listed in the table. They are similar to other spacing diacritics in Unicode, such as `´` (U+00B4 Acute Accent), which is equivalent to a space plus the combining acute accent. They are occasionally useful for showing the diacritics in isolation, but aren't otherwise used in normal text.

**Pull request merged**
